# Generated by Django 4.1 on 2024-12-19 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app3', '0002_publicacion_imagenpub_alter_comentario_autocom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='usrRel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos', to=settings.AUTH_USER_MODEL),
        ),
    ]
